# Generated by Django 6.0.5 on 2026-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produk",
            name="gambar",
            field=models.ImageField(blank=True, null=True, upload_to="produk_images/"),
        ),
        migrations.AddField(
            model_name="produk",
            name="kategori",
            field=models.CharField(default="Umum", max_length=100),
        ),
    ]
